version: "3.8"
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app_network

  backend:
    build: ./backend
    env_file:
      - .env
    ports:
      - "5000:5000"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge